'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import { 
  ArrowRight, 
  Sparkles, 
  Brain, 
  Heart, 
  Shield,
  Users,
  Star
} from 'lucide-react'
import { Button } from '@/components/ui/button'

// Animation constants
const fadeIn = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.5 }
}

const staggerContainer = {
  initial: { opacity: 0 },
  animate: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1
    }
  }
}

const SectionHeader = ({ title, subtitle, center = true }) => (
  <motion.div 
    initial={{ opacity: 0, y: 20 }}
    whileInView={{ opacity: 1, y: 0 }}
    viewport={{ once: true, margin: "-20px" }}
    className={`${center ? 'text-center' : ''} mb-14`}
  >
    <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">
      {title}
    </h2>
    <p className="text-xl text-gray-600 max-w-2xl mx-auto">
      {subtitle}
    </p>
  </motion.div>
)

const FeatureCard = ({ icon: Icon, title, description }) => (
  <motion.div
    variants={fadeIn}
    className="bg-white p-8 rounded-2xl border border-gray-100 hover:shadow-lg transition-all"
  >
    <div className="w-12 h-12 bg-emerald-50 rounded-xl flex items-center justify-center mb-6">
      <Icon className="w-6 h-6 text-emerald-600" />
    </div>
    <h3 className="text-xl font-semibold text-gray-900 mb-3">
      {title}
    </h3>
    <p className="text-gray-600 leading-relaxed">
      {description}
    </p>
  </motion.div>
)

const TestimonialCard = ({ quote, author, condition }) => (
  <motion.div
    variants={fadeIn}
    className="bg-gray-50 p-8 rounded-2xl border border-gray-100"
  >
    <div className="flex mb-4 text-amber-500">
      {[...Array(5)].map((_, i) => (
        <Star key={i} className="w-5 h-5 fill-current" />
      ))}
    </div>
    <p className="text-gray-700 mb-4 italic">"{quote}"</p>
    <div>
      <p className="font-semibold text-gray-900">{author}</p>
      <p className="text-sm text-gray-600">{condition}</p>
    </div>
  </motion.div>
)

export default function Home() {
  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Plans',
      description: 'Personalized meal plans generated by advanced AI for your specific health conditions'
    },
    {
      icon: Heart,
      title: 'Health Focused',
      description: 'Specialized support for diabetes, PCOS, heart disease, and 15+ conditions'
    },
    {
      icon: Shield,
      title: 'Secure & Private',
      description: 'HIPAA compliant platform with enterprise-grade security for your data'
    }
  ]

  const testimonials = [
    {
      quote: "My blood sugar levels have never been more stable. This app changed my life.",
      author: "Sarah M.",
      condition: "Type 2 Diabetes"
    },
    {
      quote: "Finally, meal plans that understand PCOS. I've lost 20 pounds in 3 months!",
      author: "Jennifer K.",
      condition: "PCOS"
    },
    {
      quote: "The AI recommendations are spot-on. My doctor is impressed with my progress.",
      author: "Michael R.",
      condition: "Hypertension"
    }
  ]

  return (
    <main className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="relative overflow-hidden px-4 py-20 sm:px-6 lg:px-8">
        <div className="absolute inset-0 bg-gradient-to-br from-emerald-50/70 via-white to-blue-50/70" />
        
        <div className="relative max-w-4xl mx-auto py-16 text-center">
          <motion.div
            initial="initial"
            animate="animate"
            variants={staggerContainer}
          >
            {/* Badge */}
            <motion.div
              variants={fadeIn}
              className="inline-flex items-center px-4 py-1.5 mb-8 text-sm font-medium text-emerald-700 bg-emerald-100 rounded-full"
            >
              <Sparkles className="w-4 h-4 mr-2" />
              AI-Powered Nutrition Platform
            </motion.div>

            {/* Headline */}
            <motion.h1
              variants={fadeIn}
              className="text-4xl sm:text-5xl lg:text-6xl font-bold text-gray-900 tracking-tight"
            >
              Your Personal{' '}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-600 to-blue-600">
                AI Nutritionist
              </span>
            </motion.h1>

            {/* Subheadline */}
            <motion.p
              variants={fadeIn}
              className="mt-6 text-xl text-gray-600 max-w-3xl mx-auto"
            >
              Transform your health with personalized meal plans designed for your specific conditions. 
            </motion.p>

            {/* CTA Buttons */}
            <motion.div
              variants={fadeIn}
              className="mt-10 flex flex-col sm:flex-row gap-3 justify-center"
            >
              <Link href="/auth/signup" className="flex">
                <Button size="lg" className="px-6 py-5 text-base">
                  Start Free Trial
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </Link>
              <Link href="/generate" className="flex">
                <Button size="lg" variant="outline" className="px-6 py-5 text-base">
                  Try Demo
                </Button>
              </Link>
            </motion.div>

            {/* Trust indicators */}
            <motion.div
              variants={fadeIn}
              className="mt-12 flex flex-wrap justify-center gap-6 text-sm text-gray-600"
            >
              <div className="flex items-center gap-2">
                <Shield className="w-4 h-4 text-emerald-600" />
                <span>HIPAA Compliant</span>
              </div>
              <div className="flex items-center gap-2">
                <Users className="w-4 h-4 text-emerald-600" />
                <span>10,000+ Users</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="flex text-amber-500">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="w-4 h-4 fill-current" />
                  ))}
                </div>
                <span>4.9/5 Rating</span>
              </div>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-gray-50">
        <div className="max-w-5xl mx-auto">
          <SectionHeader 
            title="Everything you need for better health" 
            subtitle="Comprehensive features designed to support your health journey" 
          />

          <motion.div
            initial="initial"
            whileInView="animate"
            viewport={{ once: true, margin: "-100px" }}
            variants={staggerContainer}
            className="grid grid-cols-1 md:grid-cols-3 gap-6"
          >
            {features.map((feature, index) => (
              <FeatureCard key={index} {...feature} />
            ))}
          </motion.div>
        </div>
      </section>

      {/* Social Proof Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-5xl mx-auto">
          <SectionHeader 
            title="Trusted by thousands" 
            subtitle="Join the community transforming their health with AI" 
          />

          <motion.div
            initial="initial"
            whileInView="animate"
            viewport={{ once: true, margin: "-100px" }}
            variants={staggerContainer}
            className="grid grid-cols-1 md:grid-cols-3 gap-6"
          >
            {testimonials.map((testimonial, index) => (
              <TestimonialCard key={index} {...testimonial} />
            ))}
          </motion.div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 bg-gradient-to-r from-emerald-900 to-gray-900">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="max-w-3xl mx-auto text-center"
        >
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-6">
            Ready to transform your health?
          </h2>
          <p className="text-xl text-emerald-100 mb-8">
            Start your free trial today. No credit card required.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Link href="/auth/signup" className="flex">
              <Button size="lg" className="px-6 py-5 text-base bg-white text-gray-900 hover:bg-gray-100">
                Start Free Trial
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
            <Link href="/pricing" className="flex">
              <Button size="lg" variant="outline" className="px-6 py-5 text-base border-white text-white hover:bg-white/10">
                View Pricing
              </Button>
            </Link>
          </div>
          <p className="mt-8 text-sm text-emerald-200">
            ✓ 14-day free trial ✓ Cancel anytime ✓ No credit card required
          </p>
        </motion.div>
      </section>
    </main>
  )
}
